iapiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-helm-image-tags
  namespace: production
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: app-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: KarthikaRajarethinam
        email: karthika.rajarethinam@igreendata.com.au
      messageTemplate: |
        chore: update images
    push:
      branch: main
  update:
    strategy: Setters
