apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-repo
  namespace: production
spec:
  interval: 1m
  url: https://github.com/KarthikaRajarethinam/dryrun-cicd  # <-- set this
  ref:
    branch: main
