apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: production
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-repo
  path: ./cloud-dry-run/flux-gitops/clusters/production
  wait: true
