apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microservice-b
  namespace: production
spec:
  interval: 1m
  chart:
    spec:
      chart: cloud-dry-run/charts/microservice-b
      sourceRef:
        kind: GitRepository
        name: dryrun-cicd
        namespace: production
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: australia-southeast1-docker.pkg.dev/das-terraform-dry-run/das-docker-repo/microservice-b
      tag: "latest" # {"$imagepolicy": "production:microservice-b:tag"}
