name: Frontend Pipeline

on:
  workflow_call:
    inputs:
      docker_compose_file:
        required: false
        type: string
        default: docker-compose.yml
      service_name:
        required: false
        type: string
        default: frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history (optional)

      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/30467746746/locations/global/workloadIdentityPools/github-cicd/providers/github'
          service_account: 'cicd-gitops@das-terraform-dry-run.iam.gserviceaccount.com'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev --quiet

      - name: Build frontend image
        run: |
          echo "Building service: ${{ inputs.service_name }}"
          docker compose -f ${{ inputs.docker_compose_file }} build ${{ inputs.service_name }}

      - name: Push frontend image
        run: |
          echo "Pushing service: ${{ inputs.service_name }}"
          docker compose -f ${{ inputs.docker_compose_file }} push ${{ inputs.service_name }}
