name: Main Controller Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  detect-and-dispatch:
    runs-on: ubuntu-latest

    outputs:
      changed-a: ${{ steps.set.outputs.a }}
      changed-b: ${{ steps.set.outputs.b }}
      changed-frontend: ${{ steps.set.outputs.frontend }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect Changes
        id: set
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          echo "a=false" >> $GITHUB_OUTPUT
          echo "b=false" >> $GITHUB_OUTPUT
          echo "frontend=false" >> $GITHUB_OUTPUT

          if echo "$CHANGED_FILES" | grep -q '^cloud-dry-run/backend/microservice-a/'; then
            echo "a=true" >> $GITHUB_OUTPUT
          fi
          if echo "$CHANGED_FILES" | grep -q '^cloud-dry-run/backend/microservice-b/'; then
            echo "b=true" >> $GITHUB_OUTPUT
          fi
          if echo "$CHANGED_FILES" | grep -q '^cloud-dry-run/backend/frontend/'; then
            echo "frontend=true" >> $GITHUB_OUTPUT
          fi

  call-microservice-a:
    needs: detect-and-dispatch
    if: needs.detect-and-dispatch.outputs.changed-a == 'true'
    uses: ./.github/workflows/microservice-a.yml

  call-microservice-b:
    needs: detect-and-dispatch
    if: needs.detect-and-dispatch.outputs.changed-b == 'true'
    uses: ./.github/workflows/microservice-b.yml

  call-frontend:
    needs: detect-and-dispatch
    if: needs.detect-and-dispatch.outputs.changed-frontend == 'true'
    uses: ./.github/workflows/frontend.yml
