name: Microservice A CI

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Build & Push
        run: |
          docker build -t australia-southeast1-docker.pkg.dev/das-terraform-dry-run/das-docker-repo/microservice-a:latest ./cloud-dry-run/backend/microservice-a
          echo "${{ secrets.GCP_AUTH }}" | docker login -u _json_key --password-stdin https://australia-southeast1-docker.pkg.dev
          docker push australia-southeast1-docker.pkg.dev/das-terraform-dry-run/das-docker-repo/microservice-a:latest
